name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Set up kubectl
      uses: aws/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy with Helm
      run: helm upgrade --install socks-shop ./socks-shop
